name: publish

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    create-docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Login to Github Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.TOKEN_CD}}
            
            - name: Build the tenant-rabbit Docker image
              run: |
                docker build . --tag ghcr.io/iyustlop/tesla-landing:latest
                docker push ghcr.io/iyustlop/tesla-landing:latest

    deploy:
        needs: create-docker-image
        runs-on: ubuntu-latest
        steps:
            - name: Install sshpass
              run: sudo apt-get install -y sshpass

            - name: SSH into Server
              run: |
                sshpass -p 
